### ISSUE TITLE
Add support for context to handle tf variables better

### ISSUE THREAD

**Issue by maquis196** [NikolaLohinski/terraform-provider-jinja#10]
Example;

I build a dict elsewhere and lets call it "local.cp_codes"

```
{[
   "test.com" = 1312
   "foo.com" = 1324
]}
```

but pass in local.cp_codes to "context" and you only see the data with no reference for it. so I have to 

```
locals {
  j2_cp_codes       = jsonencode({ "cp_codes" = local.cp_codes })
}
```

to work around this, but for terraform templating you can just;

    cp_codes       = local.cp_codes

**Comment by NikolaLohinski** [comment]
Hey @maquis196 

I am not sure I follow. The local.cp_codes your exposing in your example is not a valid tf object.

Moreover, the object passed to the provider as context has to be marshaled as JSON or YAML so as to be cast to Go struct in the code. It is also impossible to partially type terraform types in the schema when implementing the provider so passing a raw terraform object is just not possible cause the provider can't take an "any" object in.

**Comment by maquis196** [comment]
Hi, my initial example should have been;

```
cp_codes = {
  "website1.com" = "1486728"
  "website2.com" = "1486673"
  "website3.com" = "1486835"
}
```

I can see the native templatefile still takes a "key = value" being passed to it. I think in this instance, it was hoping to skip the jsonencode part first, but the more I use it, the more it just works and isn't really a problem. 

I'll close this, thanks for the provider btw, its been a life safer with akamai configs!
