### ISSUE TITLE
Allow for leveraging environment variables

### ISSUE THREAD

**Issue by secoprooster** [NikolaLohinski/terraform-provider-jinja#11]
Hi,

I haven't found a way to reference environment variables in order to populate the template during rendering. Consider a case where the .j2 file is resident on the local system and we want to render that during an "initial setup"/"bootstrap" situation.

It would be awesome if a built in function could be included in the jinja library that allows us to reference for example:

inventory = /path/{{ env['ENVIRONMENT_VARIABLE_KEY'] }} which would load the environment key named "ENVIRONMENT_VARIABLE_KEY" value - ultimate goal is to dynamically generate a .cfg file from a .j2 template with input variables determining the state of the configuration file.

Currently it looks like 'env' is not a supported function but it would be great if a function like this could be included.

If it's already supported, please let me know, I tried using {{ VARIABLE_NAME }} but I think that may require TF variables to be set first. Ideally I wouldn't want to micro-manage the variables.tf file - for example if terraform secrets are being set from Github secrets and workflow execution is occurring via git actions, passing environment variables to the terraform host and using those in templates would be advantageous. 

I may be mistaking how this provider is designed to work, so this may not be an issue.
 
For your consideration. Thanks heaps.

**Comment by secoprooster** [comment]
Closing this as I was trying to use this provider wrong. I achieved the outcome I needed by leveraging template_file data resource and local_file resources to achieve the desired find/replace based on terraform defined variables. Works well enough for my use case.

**Comment by NikolaLohinski** [comment]
Hey @secoprooster 

I think having a env filter/global still makes sense though

I am in the process of removing any non Python filter from the base filters of gonja, and moving them in an extension pack, that this terraform provider would use by default.

I'll keep your request in mind when I have time to tackle this. Thanks for your interest though 🙇 

Cheers

**Comment by secoprooster** [comment]
Awesome thank you

**Comment by NikolaLohinski** [comment]
Reopening as v2 is on its way and I want this env filter yo be part of it (cf. https://github.com/NikolaLohinski/terraform-provider-jinja/blob/feature/v2/lib/filters.go)

**Comment by NikolaLohinski** [comment]
Done in [`v2.0.0`](https://github.com/NikolaLohinski/terraform-provider-jinja/tree/v2.0.2)
