### ISSUE TITLE
[question] example folder is working?

### ISSUE THREAD

**Issue by codebydant** [NikolaLohinski/terraform-provider-jinja#12]
Hi @NikolaLohinski 

Hope you are doing well.

I was wondering if the provided example is working since i got the following error when running the plan:

![image](https://github.com/NikolaLohinski/terraform-provider-jinja/assets/115469901/bbb4132d-fbf6-48bc-a8d4-cfbf3eff9d35)

**Comment by codebydant** [comment]
I managed to make it work with the example here https://registry.terraform.io/providers/NikolaLohinski/jinja/latest/docs/data-sources/template#schema

![image](https://github.com/NikolaLohinski/terraform-provider-jinja/assets/115469901/493ad20c-3a2d-4ee7-95ed-523806c5dd07)

**Comment by NikolaLohinski** [comment]
Hi @dtcMLOps

The example is working but with the new v2 version of the provider I am currently preparing but have not released yet.

If you checked out one of the earlier tags (say 1.17.0), the example would be accurate with the latest released version of the provider.

Cheers
