### ISSUE TITLE
Need Gonja v2.3.0 in this provider :)

### ISSUE THREAD

**Issue by yunarta** [NikolaLohinski/terraform-provider-jinja#16]
Hi Nikola

I've been using your provider for generating template and found that new set of method had been added into Gonja v.2.3.0, but yet has not been updated into the provider. Would love to see this happen soon :)

**Comment by NikolaLohinski** [comment]
Hi @yunarta 

I just released [`v2.4.0` ](https://github.com/NikolaLohinski/terraform-provider-jinja/tree/v2.4.0) which contains the dependency bump.

Enjoy :beer:

**Comment by yunarta** [comment]
Thanks a lot. Appreciate your work on this awesome provider and gonja.
