### ISSUE TITLE
`trim` filter discrepancy with Python Jinja

### ISSUE THREAD

**Issue by ezdac** [NikolaLohinski/terraform-provider-jinja#8]
I noticed a minor issue with the `trim` filter:

The provider documentation claims that this filter complies to the python call-signature.
It makes it seem like you could change the default argument:

> Strip leading and trailing characters, by default whitespace.

In practice it expects no arguments and **only** trims whitespace:
https://github.com/NikolaLohinski/gonja/blob/95a2e9ebc2bc06ccf01faee844bfc8cf5586d302/builtins/filters.go#L1097-L1102

I guess it is fine that it does not implement the feature, but it would be easier discoverable if that was represented in the documentation.

**Comment by NikolaLohinski** [comment]
Hi @ezdac and thanks a lot for your feedback :pray:  . I'll get this fixed in the next release of https://github.com/NikolaLohinski/gonja and propagate the fix in here right after.

Meanwhile, I added it in https://github.com/NikolaLohinski/gonja/issues/3#issuecomment-1521937522 for tracking.

**Comment by NikolaLohinski** [comment]
Fixed in [`v1.13.3`](https://github.com/NikolaLohinski/terraform-provider-jinja/tree/v1.13.3). Let me know if that works for you @ezdac and feel free to close the issue and leave me a :star: if so.  

Cheers :pray:

**Comment by NikolaLohinski** [comment]
Closing as this seems to be fixed
