### ISSUE TITLE
Support regex to match ip addresses and cidr

### ISSUE THREAD

**Issue by cepitacio** [NikolaLohinski/terraform-provider-jinja#9]
First of all, thank you for this excellent provider!

I've been going through the documentation, but it appears that there's no mention of regular expression (regex) support. I also noticed that the match filter mentioned in the documentation is throwing an error, as follows:

```
Unable to evaluate filter &{<Token[Name] Val='match' Pos=25957 Line=566 Col=52> match [^[0-9]+] map[]}: Filter "match" not found
```

Example:

I would like to propose the addition of regex support for a use case where I need to check if a string, such as 10.2.3.4, matches an IP address or a CIDR notation, like 10.10.3.4/24.

Thank you!

**Comment by NikolaLohinski** [comment]
Hi @Cesar-EF and thank you for your interest 🙇 

The match filter should be there though to fit your needs. Are you sure you're using the latest version of the provider ?

Regarding a more general regexp filter, feel free to submit a PR for it : something like group extraction would be nice for example, but I am not sure it s the use case you've been looking for 

Cheers

**Comment by NikolaLohinski** [comment]
Closing as this is stale. And the feature does exists with the `match` filter
